all:
  children:
    docker:
      children:
        swarm_masters:
        swarm_workers:

    swarm_master:
      hosts:
        docker01:
          ansible_host: 192.168.160.11
        docker02:
          ansible_host: 192.168.160.12
        docker03:
          ansible_host: 192.168.160.13

    swarm_workers:
      hosts:
        docker04:
          ansible_host: 192.168.160.14
        docker05:
          ansible_host: 192.168.160.15
        docker06:
          ansible_host: 192.168.160.16
