mem_gb: "16"
cpu: "4"
additional_disks:
  - size_gb: "120"
    datastore_name: "VSAN_Datastore"

disk_additional_disks:
  - disk: /dev/sdb
    fstype: ext4
    mount_options: defaults
    mount: /var/lib/docker
    user: root
    group: root
    disable_periodic_fsck: false
