---

- name: add glusterfs ppa repo
  apt_repository:
    validate_certs: no
    repo: 'ppa:gluster/glusterfs-7'
    filename: glusterfs-7
    update_cache: yes
    state: present

- name: install glusterfs 7
  apt:
    name: glusterfs-server
    state: present

- name: Ensure that the glusterfs service is enabled and started at boot time
  service:
    name: glusterd
    enabled: yes
    state: restarted

- name: add peers to gluster cluster
  command: gluster peer probe {{ ansible_hostname }}
  delegate_to: docker[0]

- name: check the peer list and register output
  command: gluster peer status
  register: output

- debug:
    msg: "{{ output }}"