---

- name: add glusterfs ppa repo
  apt_repository:
    validate_certs: no
    repo: 'ppa:gluster/glusterfs-7'
    filename: glusterfs-7
    update_cache: yes
    state: present

- name: install glusterfs 7
  apt:
    name: glusterfs-server
    state: present

- name: Ensure that the glusterfs service is enabled and started at boot time
  service:
    name: glusterd
    enabled: yes
    state: restarted

- name: add peers to gluster cluster
  gluster_peer:
    state: present
    nodes: "{{ play_hosts }}"
  delegate_to: "{{ play_hosts | first }}"

- name: check the peer list and register output
  command: "gluster peer status | grep Number"
  register: output

- debug:
    msg: "{{ output }}"

- name: create glusterfs brick dir
  file:
    path: /data/glusterfs/brick01
    state: directory

