version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - /data/app/techtalk/examples/wordpress/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: $DB_ROOT
       MYSQL_DATABASE: $WP_DB
       MYSQL_USER: $WP_DB_USER
       MYSQL_PASSWORD: $WP_DB_PASS

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: $WP_DB_USER
       WORDPRESS_DB_PASSWORD: $WP_DB_PASS
       WORDPRESS_DB_NAME: $WP_DB
