---

- hosts: gluster
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: disk

- hosts: gluster
  gather_facts: yes
  become: yes
  roles:
    - role: glusterfs
      gluster_version: 7


