- hosts: docker[0]
  gather_facts: yes
  become: yes
  tasks:
    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh1
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "16384"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh2
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "32768"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh3
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "65536"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.ip_local_port_range
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: "1024 65535"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.tcp_fin_timeout
      sysctl:
        name: net.ipv4.tcp_fin_timeout
        value: "15"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: "4096"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: "4096"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.core.rmem_max
      sysctl:
        name: net.core.rmem_max
        value: "16777216"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.core.wmem_max
      sysctl:
        name: net.core.wmem_max
        value: "16777216"
        sysctl_set: yes
        state: present
        reload: yes




    - name: Start 10k containers
      docker_swarm_service:
        name: "10k_subs"
        image: rancher/hello-world
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        replicas: 10
        update_config:
          parallelism: 5
        state: present
