- hosts: docker[0]
  gather_facts: yes
  become: yes
  tasks:
#    - name: Remove old overlapping mesh network # has the same 10.0.0./24 range
#      docker_network:
#        name: ingress
#        state: absent
#        force: yes
#
#    - name: Create 10k overlay network
#      docker_network:
#        name: "10k_subs"
#        driver: overlay
#        ipam_config:
#          - subnet: "10.0.0.0/8"
#            gateway: "10.0.0.1"
#            iprange: "10.0.0.0/8"

    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh1
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "16384"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh2
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "32768"
        sysctl_set: yes
        state: present
        reload: yes
    - name: tune sysctl parameters for net.ipv4.neigh.default.gc_thresh3
      sysctl:
        name: net.ipv4.neigh.default.gc_thresh1
        value: "65536"
        sysctl_set: yes
        state: present
        reload: yes




    - name: Start 10k containers
      docker_swarm_service:
        name: "10k_subs"
        image: rancher/hello-world
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        replicas: 10
        state: present
