---
- name: remove conflicting ubuntu pacakges
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: install needed prerequiremts
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: present

- name: add the offial Docker repo GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add the offial Docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present
    filename: docker.io
    update_cache: yes

- name: Install the offical docker packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present