all:
  children:
    docker:
      hosts:
        docker01:
          ansible_host: 192.168.160.11
        docker02:
          ansible_host: 192.168.160.12
        docker03:
          ansible_host: 192.168.160.13
        docker04:
          ansible_host: 192.168.160.14

