all:
  children:
    docker:
      hosts:
        docker01.watteel.lan:
          vars:
            network_ip: 192.168.160.11
        docker02.watteel.lan:
          vars:
            network_ip: 192.168.160.12
        docker03.watteel.lan:
          vars:
            network_ip: 192.168.160.13
        docker04.watteel.lan:
          vars:
            network_ip: 192.168.160.14

