all:
  children:
    docker:
      hosts:
        docker01.watteel.lan:
          ansible_host: 192.168.160.11
        docker02.watteel.lan:
          ansible_host: 192.168.160.12
        docker03.watteel.lan:
          ansible_host: 192.168.160.13
        docker04.watteel.lan:
          ansible_host: 192.168.160.14

